name: Build Images

on:
  push:
    branches: master
  pull_request:
    paths:
      - docker-compose.yml
      - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

      # 登录Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建镜像
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain

      # 重新标记镜像
      - name: Tag Docker image
        run: |
          IMAGE_ID=$(docker images --filter "label=profile=${{ matrix.profile }}" --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          docker tag $IMAGE_ID${{ secrets.DOCKER_USERNAME }}/${{ matrix.profile }}:latest

      # 推送镜像到Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.profile }}:latest
